<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\support\Str;
use Illuminate\support\Facades\DB;

class VehicleMakeSeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        $vehicle_makes = [
            ['id' => 1, 'make_name' => 'Acura'],
            ['id' => 2, 'make_name' => 'Alfa-Romeo'],
            ['id' => 3, 'make_name' => 'Aprilia'],
            ['id' => 4, 'make_name' => 'Ashok-Leyland'],
            ['id' => 5, 'make_name' => 'Aston'],
            ['id' => 6, 'make_name' => 'Atco'],
            ['id' => 7, 'make_name' => 'Audi'],
            ['id' => 8, 'make_name' => 'Austin'],
            ['id' => 9, 'make_name' => 'Bajaj'],
            ['id' => 10, 'make_name' => 'Bentley'],
            ['id' => 11, 'make_name' => 'BMW'],
            ['id' => 12, 'make_name' => 'Cadillac'],
            ['id' => 13, 'make_name' => 'Cal'],
            ['id' => 14, 'make_name' => 'CAT'],
            ['id' => 15, 'make_name' => 'Ceygra'],
            ['id' => 16, 'make_name' => 'Changan'],
            ['id' => 17, 'make_name' => 'Chery'],
            ['id' => 18, 'make_name' => 'Chevrolet'],
            ['id' => 19, 'make_name' => 'Chrysler'],
            ['id' => 20, 'make_name' => 'Citroen'],
            ['id' => 21, 'make_name' => 'Corvette'],
            ['id' => 22, 'make_name' => 'Daewoo'],
            ['id' => 23, 'make_name' => 'Daido'],
            ['id' => 24, 'make_name' => 'Daihatsu'],
            ['id' => 25, 'make_name' => 'Datsun'],
            ['id' => 26, 'make_name' => 'Demak'],
            ['id' => 27, 'make_name' => 'Dfac'],
            ['id' => 28, 'make_name' => 'DFSK'],
            ['id' => 29, 'make_name' => 'Ducati'],
            ['id' => 30, 'make_name' => 'Eicher'],
            ['id' => 31, 'make_name' => 'FAW'],
            ['id' => 32, 'make_name' => 'Ferrari'],
            ['id' => 33, 'make_name' => 'Fiat'],
            ['id' => 34, 'make_name' => 'Force'],
            ['id' => 35, 'make_name' => 'Ford'],
            ['id' => 36, 'make_name' => 'Foton'],
            ['id' => 37, 'make_name' => 'Hero'],
            ['id' => 38, 'make_name' => 'Hero-Honda'],
            ['id' => 39, 'make_name' => 'Higer'],
            ['id' => 40, 'make_name' => 'Hillman'],
            ['id' => 41, 'make_name' => 'HINO'],
            ['id' => 42, 'make_name' => 'Hitachi'],
            ['id' => 43, 'make_name' => 'Honda'],
            ['id' => 44, 'make_name' => 'Hummer'],
            ['id' => 45, 'make_name' => 'Hyundai'],
            ['id' => 46, 'make_name' => 'Isuzu'],
            ['id' => 47, 'make_name' => 'Iveco'],
            ['id' => 48, 'make_name' => 'JAC'],
            ['id' => 50, 'make_name' => ' Jaguar'],
            ['id' => 51, 'make_name' => 'JCB'],
            ['id' => 52, 'make_name' => 'Jeep'],
            ['id' => 53, 'make_name' => 'JiaLing'],
            ['id' => 55, 'make_name' => 'JMC'],
            ['id' => 56, 'make_name' => 'John-Deere'],
            ['id' => 57, 'make_name' => 'Jonway'],
            ['id' => 58, 'make_name' => 'KAPLA'],
            ['id' => 59, 'make_name' => 'Kawasaki'],
            ['id' => 60, 'make_name' => 'Kia'],
            ['id' => 61, 'make_name' => 'Kinetic'],
            ['id' => 62, 'make_name' => 'KMC'],
            ['id' => 63, 'make_name' => 'Kobelco'],
            ['id' => 64, 'make_name' => 'Komatsu'],
            ['id' => 65, 'make_name' => 'KTM'],
            ['id' => 66, 'make_name' => 'Kubota'],
            ['id' => 67, 'make_name' => 'Lamborghini'],
            ['id' => 68, 'make_name' => 'Land-Rover'],
            ['id' => 69, 'make_name' => 'Lexus'],
            ['id' => 70, 'make_name' => 'Loncin'],
            ['id' => 71, 'make_name' => 'Longjia'],
            ['id' => 72, 'make_name' => 'Lotus'],
            ['id' => 73, 'make_name' => 'Lti'],
            ['id' => 74, 'make_name' => 'Mahindra'],
            ['id' => 75, 'make_name' => 'Maserati'],
            ['id' => 76, 'make_name' => 'Massey-Ferguson'],
            ['id' => 77, 'make_name' => 'Mazda'],
            ['id' => 78, 'make_name' => 'Mercedes-Benz'],
            ['id' => 79, 'make_name' => 'Metrocab'],
            ['id' => 80, 'make_name' => 'MG'],
            ['id' => 81, 'make_name' => 'Mg-Rover'],
            ['id' => 82, 'make_name' => 'Micro'],
            ['id' => 83, 'make_name' => 'Mini'],
            ['id' => 84, 'make_name' => 'Minnelli'],
            ['id' => 85, 'make_name' => 'Mitsubishi'],
            ['id' => 86, 'make_name' => 'Morgan'],
            ['id' => 87, 'make_name' => 'Morris'],
            ['id' => 88, 'make_name' => 'New-Holland'],
            ['id' => 89, 'make_name' => 'Nissan'],
            ['id' => 90, 'make_name' => 'Opel'],
            ['id' => 91, 'make_name' => 'Other'],
            ['id' => 92, 'make_name' => 'Perodua'],
            ['id' => 93, 'make_name' => 'Peugeot'],
            ['id' => 94, 'make_name' => 'Piaggio'],
            ['id' => 95, 'make_name' => 'Porsche'],
            ['id' => 96, 'make_name' => 'Powertrac'],
            ['id' => 97, 'make_name' => 'Proton'],
            ['id' => 98, 'make_name' => 'Range-Rover'],
            ['id' => 99, 'make_name' => 'Ranomoto'],
            ['id' => 100, 'make_name' => 'Renault'],
            ['id' => 101, 'make_name' => 'Reva'],
            ['id' => 102, 'make_name' => 'Rolls-Royce'],
            ['id' => 103, 'make_name' => 'Saab'],
            ['id' => 104, 'make_name' => 'Sakai'],
            ['id' => 105, 'make_name' => 'Seat'],
            ['id' => 106, 'make_name' => 'Singer'],
            ['id' => 107, 'make_name' => 'Skoda'],
            ['id' => 108, 'make_name' => 'Smart'],
            ['id' => 109, 'make_name' => 'Sonalika'],
            ['id' => 110, 'make_name' => 'Subaru'],
            ['id' => 111, 'make_name' => 'Suzuki'],
            ['id' => 112, 'make_name' => 'Swaraj'],
            ['id' => 113, 'make_name' => 'Syuk'],
            ['id' => 114, 'make_name' => 'TAFE'],
            ['id' => 115, 'make_name' => 'Tata'],
            ['id' => 116, 'make_name' => 'Tesla'],
            ['id' => 117, 'make_name' => 'Toyota'],
            ['id' => 118, 'make_name' => 'Triumph'],
            ['id' => 119, 'make_name' => 'Vauxhall'],
            ['id' => 120, 'make_name' => 'Vespa'],
            ['id' => 121, 'make_name' => 'Volkswagen'],
            ['id' => 122, 'make_name' => 'Volvo'],
            ['id' => 123, 'make_name' => 'Wave'],
            ['id' => 124, 'make_name' => 'Willys'],
            ['id' => 125, 'make_name' => 'Yamaha'],
            ['id' => 126, 'make_name' => 'Yanmar'],
            ['id' => 127, 'make_name' => 'Yuejin'],
            ['id' => 128, 'make_name' => 'Zongshen'],
            ['id' => 129, 'make_name' => 'Zotye'],
        ];
        \DB::table('vehicle_makes')->insert($vehicle_makes);
    }

}
